const skillSuggestions = [
  "Dojo Toolkit",
  "jQuery",
  "midori",
  "MooTools",
  "Prototype JavaScript Framework",
  "YUI Library",
  "AnyChart",
  "D3.js",
  "Highcharts",
  "EaselJS",
  "JavaScript InfoVis Toolkit",
  "p5.js",
  "Pixi.js",
  "Plotly",
  "Processing.js",
  "Raphaël",
  "SWFObject",
  "Three.js",
  "Velocity.js",
  "WhitestormJS",
  "Bootstrap",
  "DHTMLX",
  "Dojo Widgets",
  "Sencha",
  "ZURB Foundation",
  "Polymer",
  "jQuery UI",
  "jQWidgets",
  "Ignite UI",
  "Kendo UI",
  "Wijmo 5",
  "OpenUI5",
  "qooxdoo",
  "SmartClient",
  "Webix",
  "WinJS",
  "Ample SDK",
  "Glow",
  "Lively Kernel",
  "Script.aculo.us",
  "JavaScript",
  "Google Closure Library",
  "Joose",
  "JsPHP",
  "Ajax library",
  "MochiKit",
  "PDF.js",
  "Rico",
  "Socket.IO",
  "Spry framework",
  "Underscore.js",
  "CSS3",
  "HTML5",
  "jQuery Mobile",
  "Mustache",
  "Jinja-JS",
  "Twig.js",
  "Jasmine",
  "Mocha",
  "QUnit",
  "Tape",
  "Unit.js",
  "AngularJS",
  "Aurelia",
  "Backbone.js",
  "Cappuccino",
  "Chaplin.js",
  "Echo",
  "Ember.js",
  "Enyo",
  "Ext JS",
  "Knockout",
  "Meteor",
  "Mojito",
  "MooTools",
  "Node.js",
  "React.js",
  "Rialto Toolkit",
  "SproutCore",
  "Vue.js",
  "Wakanda Framework",
  "Python",
  "Ruby",
  "Golang",
  "Zend",
  "Laravel",
  "PHP",
  "Rails",
  "Java",
  "JavaFX",
  "Django",
  "Flask",
  "MongoDB",
  "Postgres",
  "NoSQL",
  "CouchDB",
  "MySQL",
  "SailsJS",
  "ExpressJS",
  "Hapi",
  "Koa",
];

const tagSuggestions = [
  "networking",
  "parallel programming",
  "artificial intelligence",
  "software engineering",
  "algortihms",
  "game development",
  "web application",
  "android",
  "iOS",
  "progressive web application",
  "service worker",
  "information retrival",
];

export { skillSuggestions, tagSuggestions };
