class Visit{
    //ASSUMPTION: usermail and eventID are checked and existing.
    constructor(TicketID, UserEmail, EventID, Reason) {
        this.TicketID = TicketID; //TicketID to be autogenerated
        this.UserEmail = UserEmail; //should have a match in User class
        this.EventID = EventID; //should have a match in Event class
        this.reason = Reason
    }
    getUserEmail() {
        return this.UserEmail;
    }

    getTicketID() {
        return this.TicketID;
    }
    
    getEventID() {
        return this.EventID;
    }
    
    getReason() {
        return this.reason;
    }
    
    setTicketID(newTicketID) {
        this.TicketID = newTicketID;
    }
    
    setReason(newReason) {
        this.reason = newReason;
    }
}
